// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
using addressbook_web_tests;


namespace addressbook_web_tests
{

    [TestFixture]
    public class ContactCreationTests : AuthTestBase
    {
        [Test]
        public void ContactCreation()
        {
            List<ContactCreationData> oldContacts = app.Contact.GetContactList();
            //System.Console.Out.Write(oldContacts.Count);
            var contact = new ContactCreationData("firstf", "firstsfsdf");
           app.Contact.ContactCreation(contact);
            /*var contact1 = new ContactCreationData("Second", "Second");
            app.Contact.ContactCreation(contact1);*/

            List<ContactCreationData> newContacts = app.Contact.GetContactList();
            oldContacts.Add(contact);
            //oldContacts.Add(contact1);
            //Assert.AreEqual(oldContacts.Count + 1, newContacts.Count);


            oldContacts.Sort();
            newContacts.Sort();
            

            
            Assert.AreEqual(oldContacts, newContacts);




            /*app.Contact.InitContactCreation();
            var contact = new ContactCreationtData("Sergeev", "Sergey");
            //contact.Lastname = "";
            contact.Middlename = "";
            contact.Nickname = "1";
            contact.Home = "1";
            contact.Company = "s";
            contact.Address = "sdf";
            contact.Title = "L";

            app.Contact.FillContactForm(contact)
                        .SubmitNewContact();
            app.Auth.Logout();
                                   // Console.WriteLine(account.Username);
*/
        }

    }
}
