// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;


namespace addressbook_web_tests {

    [TestFixture]
    public class ContactCreationTests : TestBase
    {
        [Test]
        public void ContactCreation()
        {
            var contact = new ContactCreationtData("IIIIIII", "KKKKK");
            app.Contact.ContactCreation(contact);

            /*app.Contact.InitContactCreation();
            var contact = new ContactCreationtData("Sergeev", "Sergey");
            //contact.Lastname = "";
            contact.Middlename = "";
            contact.Nickname = "1";
            contact.Home = "1";
            contact.Company = "s";
            contact.Address = "sdf";
            contact.Title = "L";

            app.Contact.FillContactForm(contact)
                        .SubmitNewContact();
            app.Auth.Logout();
                                   // Console.WriteLine(account.Username);
*/


           

        }

    }
}
