// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
using addressbook_web_tests;

namespace addressbook_web_tests
{

[TestFixture]
public class GroupCreationTests : TestBase
    {
   
    [Test]
        public void GroupCreationTest()
        {
            
            GoToHomePage();
            driver.Manage().Window.Size = new System.Drawing.Size(1007, 692);
            Login(new AccountData ("admin", "secret"));
            GoToGroupsPage();
            InitGroupCreation();
            GroupData group = new GroupData("123");
            group.Header = "d2";
            group.Footer = "f2";
            FillGroupForm(group);
            SubmitGroupCreation(); 
            ReturnToGroupsPage();
            Logout();
            TearDown();
        }    

    }
}