// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;

namespace addressbook_web_tests
{

    [TestFixture]
    public class GroupRemovalTests : AuthTestBase
    {
        [SetUp]
        public void Preconditions()
        {
            app.Groups.CreateGroupIfNotExists(1);

        }
       
        [Test]
        public void GroupRemovalTest()
        {
            List<GroupData> oldGroups = GroupData.GetAll();
            //List<GroupData> oldGroups = app.Groups.GetGroupList();
            GroupData toBeRemoved = oldGroups[0];

            GroupData oldData = oldGroups[0];
            app.Groups.Remove(oldGroups[0]);
            Assert.AreEqual(oldGroups.Count - 1, app.Groups.GetGroupCount());
            List<GroupData> newGroups = GroupData.GetAll();
            oldGroups.RemoveAt(0);

            
            Assert.AreEqual(oldGroups, newGroups);

            foreach(GroupData group in newGroups)
            {
                Assert.AreNotEqual(group.Id, toBeRemoved.Id);
            }

            /* app.Navigator.GoToGroupsPage();
             app.Groups
                 .SelectGroup(5)
                 .RemoveGroup()
                 .ReturnToGroupsPage();*/
        }      
    }
}